- time complexity - O(m * n)
- space complexity - O(m * n )

In [25]:
import numpy as np

arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Insert - Two Dimentionam array

In [26]:
newarr = np.insert(arr1, 1, [[0,0,0]], axis=0)
newarr

array([[1, 2, 3],
       [0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
newarr1 = np.insert(arr1, 1, [[0,0,0]], axis=1)
newarr1

array([[1, 0, 2, 3],
       [4, 0, 5, 6],
       [7, 0, 8, 9]])

In [28]:
newarr2 = np.append(arr1, [[0,0,0]], axis=0)
newarr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0]])

Access elements of two dimentional array

In [32]:
print(arr1)
arr1[0][1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [33]:
arr1[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [38]:
def accessElement(arr, rowIndex, colIndex):
    if rowIndex >= len(arr) & colIndex >= len(arr[0]):
        print("Incorrect index")
    else:
        print(arr[rowIndex][colIndex])

In [39]:
accessElement(arr1, 1,1)

5


- Traversal two dimentional array
- Time complexity = O(mn) ; if m=n => O(n2) -> Quadratic time complexity
- Space complexity = O(1)

In [40]:
def accessElement(arr):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
            print(arr[i][j])

In [41]:
accessElement(arr1)

1
2
3
4
5
6
7
8
9


Searching two dimentional array

In [45]:
def linear_search(arr, target):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
            if arr[i][j] == target:
                return f"the element is located at {str(i)},{str(j)}"
    return "The element is not present"

In [46]:
linear_search(arr1, 10)

'The element is not present'

In [47]:
linear_search(arr1, 2)

'the element is located at 0,1'

Deletion of two dimentional array

In [48]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
newarr1 = np.delete(arr1, 1, axis=0)
newarr1

array([[1, 2, 3],
       [7, 8, 9]])

In [50]:
newarr2 = np.delete(arr1, 2, axis=1)
newarr2

array([[1, 2],
       [4, 5],
       [7, 8]])